# Generated by Django 5.0 on 2024-01-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statuse',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
