# Generated by Django 5.0 on 2024-02-08 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0002_alter_statuse_name'),
        ('tasks', '0007_alter_tasks_executor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Statuse',
            new_name='Status',
        ),
    ]
